---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source
  namespace: source
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/10 * * * *"
  rclone:
    rcloneConfigSection: "rclone-bucket"
    rcloneDestPath: "volsync-test-bucket/mysql-pv-claim"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
