---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: dest
spec:
  trigger:
    schedule: "*/5 * * * *"
  rclone:
    rcloneConfigSection: "rclone-bucket"
    rcloneDestPath: "volsync-test-bucket/mysql-pv-claim"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: 2Gi
